server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/turbo-az
    username: postgres
    password: Butterfly2001

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

